### ISSUE TITLE
Error while training TBG_dataset

### ISSUE THREAD

**Issue by chouyoudou** [mzjb/DeepH-pack#14]
Dear developer, I tried to train the TBG_dataset but failed for many reasons. 
I took 10 of the structures and tested on two devices.

CPU cluster : 
<pre><code>
/home/miniconda3/envs/deeph/lib/python3.9/site-packages/deeph/graph.py:664: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:210.)
  read_terms[key] = torch.tensor(v, dtype=default_dtype_torch)
100%|##########| 10/10 [42:54<00:00, 257.49s/it]
Finish processing 10 structures, have cost 2575 seconds
Finish saving 10 structures to ./graph/HGraph-h5-test-5l-FromDFT.pkl, have cost 2577 seconds
Atomic types: [6]
Finish loading the processed 10 structures (spinful: False, the number of atomic types: 1), cost 0 seconds
number of train set: 6
number of val set: 2
number of test set: 2
{'normalizer': False, 'boxcox': False}
Output features length of single edge: 169
The model you built has: 493210 parameters
VAL loss each out:
[7.6e+00, 2.1e+00, 6.2e+00, 3.7e-01, 7.8e-02, 5.2e+00, 5.7e-01, 5.8e-01, 4.4e+00, 8.7e-01, 4.0e+00, 4.0e-01, 1.9e-01, 1.8e+00, 2.2e+00, 2.7e+00, 1.7e-01, 2.0e+00, 9.1e-01, 6.4e-01, 2.0e-02, 2.3e-01, 8.2e-02, 6.0e-01, 7.3e-01, 1.4e+00, 4.3e+00, 1.6e+00, 4.6e+00, 1.1e+00, 2.6e+00, 2.9e+00, 2.2e-01, 6.4e-01, 1.4e+00, 5.9e-01, 1.3e-02, 1.1e+00, 1.2e+00, 2.1e-01, 4.2e-01, 4.4e-01, 2.0e+00, 4.3e-01, 7.2e-02, 1.7e+00, 3.1e-01, 1.7e+00, 8.4e-02, 1.0e+00, 2.4e-02, 3.3e+00, 1.3e-02, 4.4e-01, 6.0e-01, 1.1e-01, 2.9e+00, 2.2e+00, 1.3e-01, 2.0e+00, 2.1e+00, 2.1e-01, 1.6e-01, 9.3e-01, 4.1e-02, 3.2e+00, 5.7e-01, 2.7e+00, 1.2e-01, 2.9e+00, 3.3e+00, 8.2e-02, 6.5e-02, 3.7e-01, 1.5e-01, 5.7e-01, 4.3e-01, 8.4e-02, 5.3e-03, 1.4e-01, 1.0e+00, 1.7e+00, 2.1e-02, 2.2e-01, 2.5e+00, 2.5e-01, 1.3e-01, 1.8e-01, 1.2e+00, 2.0e-01, 3.9e-02, 1.4e-02, 8.6e-01, 1.3e+00, 5.2e-01, 3.4e+00, 2.2e-01, 7.3e+00, 1.9e+00, 1.5e-01, 1.5e-01, 2.3e-01, 1.2e+00, 4.6e-01, 8.9e-01, 3.2e-01, 3.4e+00, 2.7e+00, 1.5e+00, 6.0e-01, 3.8e+00, 6.4e+00, 4.0e+00, 6.3e-01, 1.5e+00, 1.2e-01, 4.2e+00, 8.9e+00, 6.0e-01, 2.7e+00, 1.6e-01, 1.4e+00, 2.7e+00, 6.3e-01, 1.2e+00, 3.8e-01, 5.3e+00, 2.9e-01, 4.3e-02, 9.2e-02, 4.7e-01, 5.3e-01, 4.4e-01, 1.2e+00, 2.0e+00, 7.8e-01, 8.1e-01, 2.6e-01, 6.5e-02, 5.9e-02, 7.5e+00, 8.3e-01, 6.6e-02, 2.0e-01, 3.0e+00, 4.6e-01, 4.8e-01, 9.3e-01, 1.8e+00, 7.8e-01, 4.1e-01, 3.1e-02, 1.8e-01, 1.4e-01, 5.9e+00, 4.5e+00, 2.2e+00, 4.5e-01, 5.4e-02, 3.3e+00, 4.0e-01, 8.1e-01, 4.2e-01, 3.4e-01, 5.1e-01, 3.3e-01, 1.4e+00, 6.2e-02, 6.5e+00]
max orbital: 8.9e+00 (0-based index: 117)
Traceback (most recent call last):
  File "/home/k0171/k017113/miniconda3/envs/deeph/bin/deeph-train", line 8, in <module>
    sys.exit(main())
  File "/home/k0171/k017113/miniconda3/envs/deeph/lib/python3.9/site-packages/deeph/scripts/train.py", line 20, in main
    kernel.train(train_loader, val_loader, test_loader)
  File "/home/k0171/k017113/miniconda3/envs/deeph/lib/python3.9/site-packages/deeph/kernel.py", line 565, in train
    save_model({
  File "/home/k0171/k017113/miniconda3/envs/deeph/lib/python3.9/site-packages/deeph/utils.py", line 133, in save_model
    with package.PackageExporter(model_dir, verbose=False) as exp:
TypeError: __init__() got an unexpected keyword argument 'verbose'
</code></pre>

It looks like CPU-only PyTorch is running slow for some reason. And the training stops after only one step.

wsl2 with GPU:

There is no error message  on this device, however the process is stuck here: 

<pre><code>
Graph data file: HGraph-h5-test-5l-FromDFT.pkl
Process new data file......
Found 10 structures, have cost 0 seconds
Use multiprocessing
 10%|#         | 1/10 [00:54<08:08, 54.24s/it]
</code></pre>

After processing one structure the process stops working completely meanwhile the CPU is not used at all.
The training is fine if I only take 1 structure.

Do you know how to solve these problems?

**Comment by mzjb** [comment]
## First error
The progress bar
```
100%|##########| 10/10 [42:54<00:00, 257.49s/it]
```
shows the process of generating the crystal graph file, which only needs to be done once for the same dataset. It looks like this is a lot slower than the general case, how many atoms are contained in the 10 structures?

The error
```
TypeError: __init__() got an unexpected keyword argument 'verbose'
```
is because you are using PyTorch with a newer version than 1.9.1. You can modify line 133 of the file `/home/k0171/k017113/miniconda3/envs/deeph/lib/python3.9/site-packages/deeph/utils.py`to avoid this error: remove `, verbose=False`

## Second error
Please set `multiprocessing` to `False` for the ini config file of `deeph-train`.

**Comment by chouyoudou** [comment]
Thank you very much. 

The first error was fixed.
The 10 structures contained 64 atoms respectively; It is much faster after I set the `multiprocessing` to `False`, and so does the second error.
