### ISSUE TITLE
LoadError when predicting Hamiltonian

### ISSUE THREAD

**Issue by peiyuan-NTU** [mzjb/DeepH-pack#18]
ERROR: LoadError: SystemError: memory mapping failed: No such device
Stacktrace:
 [1] systemerror(::String, ::Int32; extrainfo::Nothing) at ./error.jl:168 [2] #systemerror#48 at ./error.jl:167 [inlined]
 [3] systemerror at ./error.jl:167 [inlined]
 [4] mmap(::IOStream, ::Type{Array{UInt8,1}}, ::Tuple{Int64}, ::Int64; grow::Bool, shared::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Mmap/src/Mmap.jl:212
 [5] #mmap#9 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Mmap/src/Mmap.jl:247 [inlined]
 [6] mmap at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Mmap/src/Mmap.jl:247 [inlined] (repeats 2 times)
 [7] #4 at /home/peiyuan/.julia/packages/JSON/NeJ9k/src/Parser.jl:510 [inlined]
 [8] open(::JSON.Parser.var"#4#5"{DataType,DataType,Nothing,Bool,Bool,Int64}, ::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:325
 [9] open at ./io.jl:323 [inlined]
 [10] #parsefile#3 at /home/peiyuan/.julia/packages/JSON/NeJ9k/src/Parser.jl:509 [inlined]
 [11] parsefile(::String) at /home/peiyuan/.julia/packages/JSON/NeJ9k/src/Parser.jl:508
 [12] top-level scope at /home/peiyuan/anaconda3/envs/deep8/lib/python3.9/site-packages/deeph/inference/dense_calc.jl:64
 [13] include(::Function, ::Module, ::String) at ./Base.jl:380
 [14] include(::Module, ::String) at ./Base.jl:368
 [15] exec_options(::Base.JLOptions) at ./client.jl:296
 [16] _start() at ./client.jl:506
in expression starting at /home/peiyuan/anaconda3/envs/deep8/lib/python3.9/site-packages/deeph/inference/dense_calc.jl:64
Traceback (most recent call last):
  File "/home/peiyuan/anaconda3/envs/deep8/bin/deeph-inference", line 8, in <module>
    sys.exit(main())
  File "/home/peiyuan/anaconda3/envs/deep8/lib/python3.9/site-packages/deeph/scripts/inference.py", line 129, in main
    assert capture_output.returncode == 0
AssertionError

**Comment by mzjb** [comment]
Please check your `inference.ini` file to ensure the setting of keyword `sparse_calc_config` is vaild.

**Comment by peiyuan-NTU** [comment]
Thanks
