### ISSUE TITLE
demo with ABACUS v3.1

### ISSUE THREAD

**Issue by NanomagLab** [mzjb/DeepH-pack#29]
Hello.
I'm trying to follow the demo_abacus.

In the inference step
`deeph-inference --config inference.ini`
 
 It occur error as follow:

```
 Output subdirectories: OUT.ABACUS
Traceback (most recent call last):
  File "/home/whal1235/miniconda3/bin/deeph-inference", line 8, in <module>
    sys.exit(main())
  File "/home/whal1235/miniconda3/lib/python3.9/site-packages/deeph/scripts/inference.py", line 78, in main
    abacus_parse(OLP_dir, work_dir, data_name=f'OUT.{abacus_suffix}', only_S=True)
  File "/home/whal1235/miniconda3/lib/python3.9/site-packages/deeph/preprocess/abacus_get_data.py", line 82, in abacus_parse
    assert "WELCOME TO ABACUS" in line
AssertionError
```
 
And, my ABACUS log file is hear:
```


                              _ABACUS v3.1

               Atomic-orbital Based Ab-initio Computation at UStc

                     Website: http://abacus.ustc.edu.cn/
               Documentation: https://abacus.deepmodeling.com/
                  Repository: https://github.com/abacusmodeling/abacus-develop
                              https://github.com/deepmodeling/abacus-develop

    Start Time is Wed Mar  8 13:45:05 2023

 ------------------------------------------------------------------------------------

 READING GENERAL INFORMATION
                           global_out_dir = OUT.ABACUS/
                           global_in_card = INPUT
                               pseudo_dir =
                              orbital_dir =
                                    DRANK = 1
                                    DSIZE = 1
                                   DCOLOR = 1
                                    GRANK = 1
                                    GSIZE = 1
 The esolver type has been set to : ksdft_lcao




 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 |                                                                    |
 | Reading atom information in unitcell:                              |
 | From the input file and the structure file we know the number of   |
 | different elments in this unitcell, then we list the detail        |
 | information for each element, especially the zeta and polar atomic |
 | orbital number for each element. The total atom number is counted. |
 | We calculate the nearest atom distance for each atom and show the  |
 | Cartesian and Direct coordinates for each atom. We list the file   |
 | address for atomic orbitals. The volume and the lattice vectors    |
 | in real and reciprocal space is also shown.                        |
 |                                                                    |
 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




 READING UNITCELL INFORMATION
                                    ntype = 1
                 atom label for species 1 = C
                  lattice constant (Bohr) = 1.88972
              lattice constant (Angstrom) = 0.999996

 READING ATOM TYPE 1
                               atom label = C
                      L=0, number of zeta = 2
                      L=1, number of zeta = 2
                      L=2, number of zeta = 1
             number of atom for this type = 100
                      start magnetization = FALSE
                      start magnetization = FALSE
                      start magnetization = FALSE
                      start magnetization = FALSE_
```

I cannot find any "WELCOME TO ABACUS" line.

Is it occur only from ABACUS v3? Or have I done something wrong?

Can i remove this Assert line from python code??

Thank you.

**Comment by mzjb** [comment]
Thank you for your report. I removed this Assert in this [commit](https://github.com/mzjb/DeepH-pack/commit/0ddef6a84d9c870466151d63d18e55218c80e4a0).

**Comment by NanomagLab** [comment]
Thank you.
