### ISSUE TITLE
Error while preprocessing in TBB

### ISSUE THREAD

**Issue by wangchengDon** [mzjb/DeepH-pack#34]
Dear developer, I encountered the following error while executing the second preprocessing.
Found 20 directories to preprocess
Preprocessing No. 1/20...
/Bin/sh:/public/apps/julia-1.54/bin/jula: 
Traceback (most recent call last):
File "/public/apps/miniconda3/bin/deeph-preprocess", line 8, in <module>
sys.exit(main())
File "/public/apps/miniconda3/lib/python3.9/site-packages/deeph/scripts/preprocess.py", line 64, in main
assert capture_ output.returncode == 0
AssertionError
my proprcess.ini is as follows
[basic]
raw_dir = /public/wcd/twisted/example/work_dir/dataset/raw
processed_dir = /public/wcd/twisted/example/work_dir/dataset/processed
target = hamiltonian
interface = openmx
multiprocessing = 48
local_coordinate = Ture
get_S = False

[interpreter]
python_interpreter = /public/apps/miniconda3/bin/python3
julia_interpreter = /public/apps/julia-1.5.4/bin/juila
[graph]
radius = 9.0
create_from_DFT = True
After trying to read the source code, I couldn't figure out why capture_ Output.returncode is not 0.Could you help me with this problem?
Thank you for your response.

**Comment by mzjb** [comment]
Hi,

To address the problem, I would suggest upgrading DeepH-pack to the latest version and retrying `deeph-preprocess`.

In your error trace, there is a discrepancy between line 64 of the `deeph/scripts/preprocess.py` and [the code](https://github.com/mzjb/DeepH-pack/blob/1130ad648d8b02be96e9de0144f8f8cff886a178/deeph/scripts/preprocess.py#L64) in the latest version of the GitHub repository.
