### ISSUE TITLE
 propagate() got an unexpected keyword argument 'distance'

### ISSUE THREAD

**Issue by Dengsongquanch** [mzjb/DeepH-pack#82]
When I run the run.sh in 3_train in example, there occurs the error below:
Traceback (most recent call last):
  File "/public/home/yika/miniforge3/envs/deepH3/bin/deeph-train", line 8, in <module>
    sys.exit(main())
  File "/public/home/yika/miniforge3/envs/deepH3/lib/python3.9/site-packages/deeph/scripts/train.py", line 20, in main
    kernel.train(train_loader, val_loader, test_loader)
  File "/public/home/yika/miniforge3/envs/deepH3/lib/python3.9/site-packages/deeph/kernel.py", line 513, in train
    train_losses = self.kernel_fn(train_loader, 'TRAIN')
  File "/public/home/yika/miniforge3/envs/deepH3/lib/python3.9/site-packages/deeph/kernel.py", line 658, in kernel_fn
    output = self.model(
  File "/public/home/yika/miniforge3/envs/deepH3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/yika/miniforge3/envs/deepH3/lib/python3.9/site-packages/deeph/model.py", line 633, in forward
    atom_fea, edge_fea = self.mp1(atom_fea0, edge_idx, edge_fea0, batch, distance, edge_vec)
  File "/public/home/yika/miniforge3/envs/deepH3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/yika/miniforge3/envs/deepH3/lib/python3.9/site-packages/deeph/model.py", line 406, in forward
    atom_fea = self.cgconv(atom_fea, edge_idx, edge_fea, batch, distance)
  File "/public/home/yika/miniforge3/envs/deepH3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/yika/miniforge3/envs/deepH3/lib/python3.9/site-packages/deeph/model.py", line 145, in forward
    out = self.propagate(edge_index, x=x, edge_attr=edge_attr, distance=distance, size=size)
TypeError: propagate() got an unexpected keyword argument 'distance'   

the version of my pyg is 2.6.1,should I make it lower than 2.6.1?

**Comment by mzjb** [comment]
Please consider using the package versions specified in the README (https://github.com/mzjb/DeepH-pack?tab=readme-ov-file#python).

**Comment by Dengsongquanch** [comment]
> Please consider using the package versions specified in the README (https://github.com/mzjb/DeepH-pack?tab=readme-ov-file#python).

thank you. However, on our computer cluster, cuda is version 11.8, and pytorch1.9.1 can only find cuda11.1. Can a higher version of cuda be compatible with a lower version of pytorch?

**Comment by mzjb** [comment]
Yes, a higher system CUDA version (like 11.8) can be compatible with a lower version of PyTorch (like 1.9.1 with CUDA 11.1), as PyTorch typically uses its own built-in CUDA libraries.

**Comment by duguex** [comment]
Follow the instructions in the [README](https://github.com/mzjb/DeepH-pack?tab=readme-ov-file#python) is the best way. But if you want to run the code in the latest version of packages, you can follow the instructions of [pyg](https://pytorch-geometric.readthedocs.io/en/latest/advanced/jit.html#creating-jittable-gnn-operators) and issue [9551](https://github.com/pyg-team/pytorch_geometric/issues/9551), [9772](https://github.com/pyg-team/pytorch_geometric/issues/9772) of pytorch-geometric.

Actually, you can change the comment of /your_conda_path/envs/deeph/lib/python3.12/site-packages/deeph/model.py to run the code in the latest version of packages.

```python

def forward(self, x: Union[torch.Tensor, PairTensor], edge_index: Adj,
            edge_attr: OptTensor, batch, distance, size: Size = None) -> torch.Tensor:
    """"""
    if isinstance(x, torch.Tensor):
        x: PairTensor = (x, x)

    # propagate_type: (x: PairTensor, edge_attr: OptTensor, distance: Optional[Tensor], size: Optional[Tensor])
    ......
```

By the way, here is the package version I used to run the code:

```
# Name                    Version                   Build  Channel
deeph                     0.2.2                    pypi_0    pypi
e3nn                      0.4.4                    pypi_0    pypi
h5py                      3.12.1          nompi_py312hd203070_103    conda-forge
numpy                     2.2.1           py312h7e784f5_0    conda-forge
pathos                    0.3.0           py312h06a4308_0  
psutil                    5.9.0           py312h5eee18b_0  
pymatgen                  2024.11.13      py312hc0a28a1_0    conda-forge
python                    3.12.8          h9e4cc4f_1_cpython    conda-forge
pytorch                   2.4.1           cpu_mkl_py312hf535c18_100    conda-forge
pytorch-geometric         2.6.1           py312_torch_2.4.0_cpu    rusty1s
scipy                     1.14.1          py312h62794b6_2    conda-forge
tensorboard               2.17.0          py312h06a4308_0  
tensorboard-data-server   0.7.0           py312h52d8a92_1  
torch-scatter             2.1.1           py312hd7e3cc5_9    conda-forge
torchaudio                2.4.1           cpu_py312hd217f58_2    conda-forge
torchvision               0.19.1          cpu_py312h5ad8046_2    conda-forge
```
